---
title: "Tweaking display items: Subsampling figures"
output:   
  html_notebook: 
    toc: true
    toc_float: true
---

**J. Taroni 2018**

## Set up 

```{r setup}
knitr::opts_knit$set(root.dir = "..")
```

```{r}
`%>%` <- dplyr::`%>%`
```

```{r}
plot.dir <- file.path("figure_notebooks", "figures")
```

## Plotting

### Plot functions

```{r}
base_theme <- function() {
  ggplot2::theme_bw() +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5),
                 text = ggplot2::element_text(size = 15))
}
```

### Number of latent variables

```{r}
num.lvs.file <- file.path("results", "17", "number_of_LVs.tsv")
num.lvs.df <- readr::read_tsv(num.lvs.file)
```

```{r}
num.lvs.p <- num.lvs.df %>%
  dplyr::mutate(training_set = 
                  dplyr::if_else(training_set == "recount2 subsampled",
                                 "recount2", training_set)) %>%
  ggplot2::ggplot(ggplot2::aes(x = training_set, y = num_lvs,
                               group = training_set)) +
  ggplot2::geom_boxplot() +
  ggplot2::geom_point(position = ggplot2::position_jitter(0.2),
                      alpha = 0.5) +
  ggplot2::labs(x = "training set", 
                y = "number of latent variables",
                title = "Number of LVs") +
  base_theme()
```


Include the metrics from the full recount2 PLIER model (see 
`02-recount2_PLIER_exploration`)

```{r}
num.lvs.p.recount <- num.lvs.p + 
  ggplot2::geom_point(data = data.frame(training_set = factor(c("recount2", 
                                                                "SLE")), 
                                        num_lvs = c(987, NA)),
                      shape = 23, size = 3, fill = "#0000FF")
```

### Pathway coverage

```{r}
pathway.file <- file.path("results", "17", "pathway_coverage.tsv")
pathway.df <- readr::read_tsv(pathway.file)
```

```{r}
pathway.cov.p <- pathway.df %>%
  dplyr::filter(pathway_coverage_type == "pathway coverage") %>%
  dplyr::mutate(training_set = 
                  dplyr::if_else(training_set == "recount2 subsampled",
                                 "recount2", training_set)) %>%
  ggplot2::ggplot(ggplot2::aes(x = training_set, y = value,
                               group = training_set)) +
  ggplot2::geom_boxplot() +
  ggplot2::geom_point(position = ggplot2::position_jitter(0.2),
                      alpha = 0.5) +
  ggplot2::ylim(c(0, 0.45)) +
  ggplot2::labs(x = "training set", 
                y = "proportion of input pathways",
                title = "Pathway Coverage") +
  base_theme()
```

Add single point representing full model 

```{r}
pathway.cov.p.recount <- pathway.cov.p + 
  ggplot2::geom_point(data = data.frame(training_set = factor(c("recount2",
                                                                "SLE")),
                                        value = c(0.4187898, NA)),
                      shape = 23, size = 3, fill = "#0000FF")
```

### LV associated with pathways

```{r}
lv.assoc.p <- pathway.df %>%
  dplyr::filter(pathway_coverage_type == "LV associated with pathways") %>%
  dplyr::mutate(training_set = 
                  dplyr::if_else(training_set == "recount2 subsampled",
                                 "recount2", training_set)) %>%
  ggplot2::ggplot(ggplot2::aes(x = training_set, y = value,
                               group = training_set)) +
  ggplot2::geom_boxplot() +
  ggplot2::geom_point(position = ggplot2::position_jitter(0.2),
                      alpha = 0.5) +
  ggplot2::ylim(c(0, 0.625)) +
  ggplot2::labs(x = "training set", 
                y = "proportion of LVs",
                title = "LVs significantly associated\nwith pathways") +
  base_theme()
```

```{r}
lv.assoc.p.recount <- lv.assoc.p + 
  ggplot2::geom_point(data = data.frame(training_set = factor(c("recount2",
                                                                "SLE")),
                                        value = c(0.2016211, NA)),
                      shape = 23, size = 3, fill = "#0000FF")
```

```{r}
p <- cowplot::plot_grid(num.lvs.p.recount, pathway.cov.p.recount, 
                        lv.assoc.p.recount, ncol = 3, scale = 0.95, 
                        labels = "AUTO")
ggplot2::ggsave(file.path(plot.dir, "subsampling_with_recount2_full.pdf"),
                plot = p, width = 11, height = 4.5)
```

